services:
  bot:
    build: ./Bot
    env_file: .env
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - bot-network

  db:
    image: postgres:16-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - bot-network

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bot-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  bot-network:
    driver: bridge
