services:
  database:
    image: "postgres:latest"
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env

  EngineerAPI:
    build: .
    image: engineerapi
    env_file:
      - .env
    depends_on:
      - database
    restart: unless-stopped

